function [ imageData, trialData ] = xmlParser( filename )
%XMLPARSER Converts xml file into trial data
%   Function takes an xml file which can be generated by the vrClient or
%   manually constructed. It then tries to convert all the data into a
%   format that is suitabe for running the actual experiment


xDoc = xmlread(filename);

% Extract general session information


% Extract image information
allImageItems = xDoc.getElementsByTagName('image');
imageData = cell(allImageItems.getLength,3);
for imageIndex = 0:(allImageItems.getLength-1)
   thisImageItem = allImageItems.item(imageIndex);
   
   % Get ID attribute
   [~,imageID] = xmlParseAttribute(getAttributes(thisImageItem));
   
   % Get name and location element
   imageNameElement =     thisImageItem.getElementsByTagName('name');
   imageLocationElement = thisImageItem.getElementsByTagName('location');
   
   imageNameItem =     item(imageNameElement,0);
   imageLocationItem = item(imageLocationElement,0);
   
   imageName =     char(imageNameItem.getFirstChild.getData);
   imageLocation = char(imageLocationItem.getFirstChild.getData);
   
   % Save data
   imageData{imageIndex+1,1} = str2double(imageID);
   imageData{imageIndex+1,2} = imageName;
   imageData{imageIndex+1,3} = imageLocation;
end

% Extract trial informaton
allTrialItems = xDoc.getElementsByTagName('trial');
trialData = cell(allTrialItems.getLength,20);

for trialIndex = 0:(allTrialItems.getLength-1)
    thisTrialItem = allTrialItems.item(trialIndex);
    
    % Get name and id attribute
    trialAttribute = getAttributes(thisTrialItem);
    [~,value] = xmlParseAttribute(trialAttribute);
    trialData{trialIndex+1,1} = str2double(value{1});
    trialData{trialIndex+1,2} = value{2};
    
    % Get reward type
    trialRewardElement = thisTrialItem.getElementsByTagName('reward');
    trialRewardItem = item(trialRewardElement,0);
    [~, type] = xmlParseAttribute(getAttributes(trialRewardItem));
    
    trialData{trialIndex+1,3} = type;
    if strcmp(type,'none')
        
    elseif strcmp(type,'random')
        rewardStartElement = trialRewardItem.getElementsByTagName('start');
        rewardStartItem = item(rewardStartElement,0);
        rewardStart = str2double(char(rewardStartItem.getFirstChild.getData));
        
        trialData{trialIndex+1,4} = rewardStart;
    elseif strcmp(type,'velocity')
        rewardThresholdElement =  trialRewardItem.getElementsByTagName('threshold');
        rewardDurationElement =   trialRewardItem.getElementsByTagName('duration');
        rewardComparisonElement = trialRewardItem.getElementsByTagName('thresholdComparison');
        
        rewardThresholdItem =  item(rewardThresholdElement,0);
        rewardDurationItem =   item(rewardDurationElement,0);
        rewardComparisonItem = item(rewardComparisonElement,0);
        
        rewardThreshold =  str2double(char(rewardThresholdItem.getFirstChild.getData));
        rewardDuration =   str2double(char(rewardDurationItem.getFirstChild.getData));
        rewardComparison = char(rewardComparisonItem.getFirstChild.getData);
        
        trialData{trialIndex+1,4} = rewardThreshold;
        trialData{trialIndex+1,5} = rewardDuration;
        trialData{trialIndex+1,6} = rewardComparison;
    end
    
    % Get transition type
    trialTransitionElement = thisTrialItem.getElementsByTagName('transition');
    trialTransitionItem = item(trialTransitionElement,0);
    [~,type] = xmlParseAttribute(getAttributes(trialTransitionItem));
    
    trialData{trialIndex+1,9} = type;
    
    if strcmp(type,'duration')
        transitionDurationElement = trialTransitionItem.getElementsByTagName('duration');
        transitionDurationItem = item(transitionDurationElement,0);
        transitionDuration = str2double(char(transitionDurationItem.getFirstChild.getData));
        
        trialData{trialIndex+1,10} = transitionDuration;
    elseif strcmp(type,'velocity')
        transitionThresholdElement = trialTransitionItem.getElementsByTagName('threshold');
        transitionDurationElement  = trialTransitionItem.getElementsByTagName('duration');
        transitionComparisonElement= trialTransitionItem.getElementsByTagName('thresholdComparison');
        
        transitionThresholdItem  = item(transitionThresholdElement,0);
        transitionDurationItem   = item(transitionDurationElement,0);
        transitionComparisonItem = item(transitionComparisonElement,0);
        
        transitionThreshold = str2double(char(transitionThresholdItem.getFirstChild.getData));
        transitionDuration = str2double(char(transitionDurationItem.getFirstChild.getData));
        transitionDurationComparison = char(transitionComparisonItem.getFirstChild.getData);
        
        trialData{trialIndex+1,10} = transitionThreshold;
        trialData{trialIndex+1,11} = transitionDuration;
        trialData{trialIndex+1,12} = transitionDurationComparison;
    end
    
    % Get stimulus properties
    trialStimulusElement = thisTrialItem.getElementsByTagName('stimulus');
    trialStimulusCount = trialStimulusElement.getLength;
    for stimulusIndex = 0:(trialStimulusCount-1)
        trialStimulusItem = item(trialStimulusElement,stimulusIndex);
        
        [~,screen] = xmlParseAttribute(getAttributes(trialStimulusItem));
        
        stimulusNameElement  = trialStimulusItem.getElementsByTagName('name');
        stimulusWidthElement = trialStimulusItem.getElementsByTagName('width');
        stimulusHeightElement= trialStimulusItem.getElementsByTagName('height');
        stimulusLeftElement  = trialStimulusItem.getElementsByTagName('left');
        stimulusTopElement   = trialStimulusItem.getElementsByTagName('top');
        
        stimulusNameItem =   item(stimulusNameElement,0);
        stimulusWidthItem =  item(stimulusWidthElement,0);
        stimulusHeightItem = item(stimulusHeightElement,0);
        stimulusLeftItem =   item(stimulusLeftElement,0);
        stimulusTopItem =    item(stimulusTopElement,0);
        
        trialData{trialIndex+1, 15 + (stimulusIndex*8)} = screen;
        trialData{trialIndex+1, 16 + (stimulusIndex*8)} = char(stimulusNameItem.getFirstChild.getData);
        trialData{trialIndex+1, 17 + (stimulusIndex*8)} = str2double(char(stimulusWidthItem.getFirstChild.getData));
        trialData{trialIndex+1, 18 + (stimulusIndex*8)} = str2double(char(stimulusHeightItem.getFirstChild.getData));
        trialData{trialIndex+1, 19 + (stimulusIndex*8)} = str2double(char(stimulusLeftItem.getFirstChild.getData));
        trialData{trialIndex+1, 20 + (stimulusIndex*8)} = str2double(char(stimulusTopItem.getFirstChild.getData));
    end
    
    
    % Future work: implement within and between trial modifier functions
end
end

