function DisplayScreenInfo( lMonitorWindow, rMonitorWindow )
%DSIPLAYSCREENINFO Displays information for windows generated by PTB
%   
    lMonitorIFI = Screen('GetFlipInterval',lMonitorWindow);
    rMonitorIFI = Screen('GetFlipInterval',lMonitorWindow);

    lMonitorHz = 1/lMonitorIFI;
    rMonitorHz = 1/rMonitorIFI;

    lMonitorNominalHz = Screen('NominalFrameRate',lMonitorWindow);
    rMonitorNominalHz = Screen('NominalFrameRate',rMonitorWindow);

    [lMonitorWidth, lMonitorHeight] = Screen('DisplaySize', lMonitorWindow);
    [rMonitorWidth, rMonitorHeight] = Screen('DisplaySize', rMonitorWindow);
    [lMonitorPixelsX, lMonitorPixelsY] = Screen('WindowSize',lMonitorWindow);
    [rMonitorPixelsX, rMonitorPixelsY] = Screen('WindowSize',rMonitorWindow);

end

